services:
  lab-http:
    image: nginx:alpine
    ports:
      - "8080:80"
    restart: unless-stopped

  juice-shop:
    image: bkimminich/juice-shop
    profiles:
      - training
    ports:
      - "3000:3000"
    restart: unless-stopped
