#!/bin/sh

for IPV4 in $(find /tmp -type f -name "newwanip_*"); do
	INTERFACE=$(cat "${IPV4}")
	rm "${IPV4}"

	echo -n "Reconfiguring IPv4 on ${INTERFACE}: "
	/usr/local/opnsense/service/configd_ctl.py interface newip ${INTERFACE}
done

for IPV6 in $(find /tmp -type f -name "newwanipv6_*"); do
	INTERFACE=$(cat "${IPV6}")
	rm "${IPV6}"

	echo -n "Reconfiguring IPv6 on ${INTERFACE}: "
	/usr/local/opnsense/service/configd_ctl.py interface newipv6 ${INTERFACE}
done
