<?php
/**
 *    Copyright (C) 2015 Deciso B.V.
 *
 *    All rights reserved.
 *
 *    Redistribution and use in source and binary forms, with or without
 *    modification, are permitted provided that the following conditions are met:
 *
 *    1. Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *
 *    2. Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 *    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 *    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 *    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 *    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 *    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 *    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 *    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *    POSSIBILITY OF SUCH DAMAGE.
 *
 */

/**
 *
 * Language support, autogenerated file
 *
 */
echo gettext('Allow access to the \'Status: IPsec: SAD\' page.');
echo gettext('Allow access to the \'VPN: PPTP: Users\' page.');
echo gettext('Allow access to the \'System: Authentication Servers\' page.');
echo gettext('Allow access to the \'Diagnostics: States Summary\' page.');
echo gettext('Allow access to the \'VPN: PPTP: User: Edit\' page.');
echo gettext('Show all items on help menu');
echo gettext('Allow access to the \'System: Firmware: Settings\' page.');
echo gettext('Allow access to the \'System: User Manager: Add Privileges\' page.');
echo gettext('Allow access to the \'Services: NTP\' page.');
echo gettext('Allow access to the \'VPN: OpenVPN: Client Specific Override\' page.');
echo gettext('Allow access to the \'VPN: OpenVPN: Client\' page.');
echo gettext('Allow access to the \'Interfaces: Assign network ports\' page.');
echo gettext('Allow access to the \'Firewall: NAT: Port Forward\' page.');
echo gettext('Allow access to the \'VPN: IPsec: Pre-Shared Keys List\' page.');
echo gettext('Create interface groups');
echo gettext('Allow access to the \'Interfaces: VLAN: Edit\' page.');
echo gettext('Allow access to the \'Diagnostics: Reboot System\' page.');
echo gettext('Allow access to the \'Load Balancer: Pool: Edit\' page.');
echo gettext('Allow access to the \'System: User Manager\' page.');
echo gettext('Allow access to the \'Services: DHCPv6 Server : Edit static mapping\' page.');
echo gettext('Allow access to the \'Load Balancer: Pool\' page.');
echo gettext('Allow access to the \'VPN: L2TP: Users : Edit\' page.');
echo gettext('Allow access to the \'Firewall: Schedules\' page.');
echo gettext('Allow access to the \'Diagnostics: Logs: Settings\' page.');
echo gettext('Allow access to the \'Service: Universal Plug and Play\' page.');
echo gettext('Allow access to the \'Firewall: Virtual IP Addresses\' page.');
echo gettext('Allow access to the \'System: Firmware: Manual Update\' page.');
echo gettext('Allow access to the \'Status: Services\' page.');
echo gettext('Allow access to the \'Status: IPsec: Leases\' page.');
echo gettext('Allow access to the \'Services: DNS Forwarder: Edit Domain Override\' page.');
echo gettext('Allow access to the \'Interfaces: PPPs\' page.');
echo gettext('Allow access to the \'Firewall: NAT: 1:1\' page.');
echo gettext('Indicates whether the user is allowed to use the proxy');
echo gettext('Allow access to the \'Status: System logs: IPsec VPN\' page.');
echo gettext('Allow access to the \'Services: DHCP Server : Edit static mapping\' page.');
echo gettext('Allow access to the \'Services: DHCPv6 server\' page.');
echo gettext('Allow access to the \'Status: System logs: Load Balancer\' page.');
echo gettext('Allow access to the \'Lobby: Login / Logout/ Dashboard\' page.');
echo gettext('Allow access to the \'Services: DNS Resolver: Edit host\' page.');
echo gettext('Allow access to the \'Services: SNMP\' page.');
echo gettext('Allow access to the \'Settings: Load Balancer: Settings\' page.');
echo gettext('Allow access to the \'Diagnostics: Show States\' page.');
echo gettext('Allow access to the \'VPN: OpenVPN: Client Export Utility\' page.');
echo gettext('Indicates whether the user is able to login for example via SSH.');
echo gettext('Allow access to the \'Status: Traffic Graph\' page.');
echo gettext('Allow access to the \'Firewall: Aliases\' page.');
echo gettext('Allow access to the \'Services: Load Balancer: Monitor: Edit\' page.');
echo gettext('Allow access to the \'System: CRL Manager\' page.');
echo gettext('Allow access to the \'Diagnostics: Interface Traffic\' page.');
echo gettext('Allow access to the \'System: Firmware: Auto Update\' page.');
echo gettext('Allow access to the \'Diagnostics: Sockets\' page.');
echo gettext('Allow access to the \'Status: Universal Plug and Play\' page.');
echo gettext('Allow access to the \'Services: PPPoE Server\' page.');
echo gettext('Allow access to the \'Status: System logs: OpenVPN\' page.');
echo gettext('Allow access to the \'Status: OpenVPN\' page.');
echo gettext('Allow access to the \'Services: RFC 2136 clients\' page.');
echo gettext('Uploads crash reports to the developers.');
echo gettext('Allow access to the \'Firewall: Alias: Edit\' page.');
echo gettext('Allow access to the \'Interfaces: PPPs: Edit\' page.');
echo gettext('Allow access to the \'Firewall: NAT: NPT\' page.');
echo gettext('Allow access to the \'Interfaces: GIF: Edit\' page.');
echo gettext('Allow access to the \'VPN: IPsec\' page.');
echo gettext('Allow access to the \'Load Balancer: Virtual Server: Edit\' page.');
echo gettext('Allow access to the \'Status: System logs: NTP\' page.');
echo gettext('Allow access to the \'Interfaces: GRE\' page.');
echo gettext('Allow access to the \'Services: Router Advertisements\' page.');
echo gettext('Allow access to the \'VPN: IPsec: Edit Phase 2\' page.');
echo gettext('Allow access to the \'System: Advanced: Networking\' page.');
echo gettext('Allow access to the \'VPN: IPsec: Edit Phase 1\' page.');
echo gettext('Allow access to the \'Interfaces: VLAN\' page.');
echo gettext('Allow access to the \'Firewall: NAT: Port Forward: Edit\' page.');
echo gettext('Allow access to the \'Services: DNS Resolver: Edit Domain Override\' page.');
echo gettext('Allow access to the \'Firewall: Alias: Import\' page.');
echo gettext('Allow access to the \'Diagnostics: Reset state\' page.');
echo gettext('Allow access to the \'Services: Wake on LAN: Edit\' page.');
echo gettext('Allow access to the \'Firewall: Virtual IP Address: Edit\' page.');
echo gettext('Allow access to the \'Diagnostics: Routing tables\' page.');
echo gettext('Allow access to the \'System: Advanced: Admin Access\' page.');
echo gettext('Allow access to the \'Status: System logs: System: Routing\' page.');
echo gettext('Allow access to the \'Status: Interfaces\' page.');
echo gettext('Allow access to the \'Services: DNS Forwarder\' page.');
echo gettext('Allow access to the \'Status: Gateways\' page.');
echo gettext('Allow access to the \'Status: DHCP leases\' page.');
echo gettext('Allow access to the \'Hidden: Detailed Status\' page.');
echo gettext('Allow access to the \'System: Advanced: Miscellaneous\' page.');
echo gettext('Allow access to the \'AJAX: Service Providers\' page.');
echo gettext('Allow access to the \'Diagnostics: Logs: Firewall: Normal View\' page.');
echo gettext('Allow access to the \'Diagnostics: Halt system\' page.');
echo gettext('Allow access to the \'Diagnostics: Logs: L2TP\' page.');
echo gettext('Allow access to the \'Services: Igmpproxy: Edit\' page.');
echo gettext('Allow access to the \'System: User Manager: Settings: Test LDAP\' page.');
echo gettext('Allow access to the \'VPN: L2TP\' page.');
echo gettext('Allow access to the \'XMLRPC Library\' page.');
echo gettext('Allow access to the \'Diagnostics: Logs: Firewall: Summary View\' page.');
echo gettext('Allow access to the \'Status: IPsec: SPD\' page.');
echo gettext('Allow access to the \'Status: Filter Reload Status\' page.');
echo gettext('Allow access to all pages');
echo gettext('Allow access to the \'Firewall: NAT: NPT: Edit\' page.');
echo gettext('Indicates whether the user is allowed to dial in via PPPOE');
echo gettext('Allow access to the \'System: Advanced: Notifications\' page.');
echo gettext('Allow access to the \'Diagnostics: Logs: DHCP\' page.');
echo gettext('Allow access to the \'System: Gateway Groups\' page.');
echo gettext('Allow access to the \'Wizard subsystem\' page.');
echo gettext('Allow access to the \'Diagnostics: Restore Full Backup\' page.');
echo gettext('Allow access to the \'Status: CARP\' page.');
echo gettext('Allow access to the \'Diagnostics: Authentication\' page.');
echo gettext('Allow access to the \'VPN: PPTP\' page.');
echo gettext('Allow access to the \'Firewall: Rules\' page.');
echo gettext('Allow access to the \'AJAX: Get Stats\' page.');
echo gettext('Allow access to the \'Diagnostics: Logs: System: Gateways\' page.');
echo gettext('Allow access to the \'Services: DHCPv6 Relay\' page.');
echo gettext('Allow access to the \'Services: DNS Resolver: Advanced\' page.');
echo gettext('Allow access to the \'Services: Load Balancer: Virtual Servers\' page.');
echo gettext('Allow access to the \'Status: NTP\' page.');
echo gettext('Allows access to the \'Diagnostics: Limiter Info\' page');
echo gettext('Allow access to the \'Diagnostics: Logs: Firewall: Plain View\' page.');
echo gettext('Allow access to the \'Diagnostics: Logs: System: Resolver\' page.');
echo gettext('Allow access to the \'Status: Wireless\' page.');
echo gettext('Allow access to the \'Status: NTP PPS\' page.');
echo gettext('Allow access to the \'Diagnostics: Logs: PPTP\' page.');
echo gettext('Allow access to the \'Diagnostics: NanoBSD\' page.');
echo gettext('Allow access to the \'System: CA Manager\' page.');
echo gettext('Allow access to all pages required for the dashboard.');
echo gettext('Allow access to the \'Diagnostics: Patterns\' page.');
echo gettext('Allow access to the \'System: User Password Manager\' page.');
echo gettext('Allow access to \'Interfaces: QinQ: Edit\' page');
echo gettext('Allow access to the \'Firewall: Rules: Edit\' page.');
echo gettext('Allow access to the \'Diagnostics: Packet Capture\' page.');
echo gettext('Allow access to the \'Services: DNS Resolver: Access Lists\' page.');
echo gettext('Allow access to the \'Firewall: NAT: Outbound: Edit\' page.');
echo gettext('Allow access to the \'Status: IPsec\' page.');
echo gettext('Allow access to the \'Interfaces: Wireless : Edit\' page.');
echo gettext('Allow access to the \'Diagnostics: Test Port\' page.');
echo gettext('Allow access to the \'Diagnostics: Logs: System\' page.');
echo gettext('Allow access to the \'VPN: L2TP : Users\' page.');
echo gettext('If present, ignores requests from this user to write config.xml.');
echo gettext('Allow access to the \'Interfaces: Groups: Edit\' page.');
echo gettext('Allow access to the \'Diagnostics: Logs: Firewall: Dynamic View\' page.');
echo gettext('Allows access to the \'Diagnostics: pfInfo\' page');
echo gettext('Indicates whether the user is allowed to dial in via IPsec xauth (Note: Does not allow shell access, but may allow the user to create ssh tunnels)');
echo gettext('Allow access to the \'Status: System logs: IPsec VPN\' page.');
echo gettext('Allow access to the \'Interfaces: LAGG: Edit\' page.');
echo gettext('Allow access to the \'VPN: OpenVPN: Server\' page.');
echo gettext('Allow access to the \'VPN: IPsec: Mobile\' page.');
echo gettext('Allow access to the \'System: Gateways: Edit Gateway\' page.');
echo gettext('Allow access to the \'Diagnostics: Backup/restore\' page.');
echo gettext('Allow direct access to all Dashboard widget pages, required for some widgets using AJAX.');
echo gettext('Allow access to the \'Status: Load Balancer: Virtual Server\' page.');
echo gettext('Allow access to the \'Diagnostics: Configuration History\' page.');
echo gettext('Allow access to the \'Interfaces: GRE: Edit\' page.');
echo gettext('Allow access to the \'Status: Gateway Groups\' page.');
echo gettext('Allow access to the \'Services: DHCP server\' page.');
echo gettext('Allow access to the \'Interfaces\' page.');
echo gettext('Allow access to the \'Services: DNS Forwarder: Edit host\' page.');
echo gettext('Allow access to the \'Status: System logs: Captive portal\' page.');
echo gettext('Allow access to the \'System: General Setup\' page.');
echo gettext('Allow access to the \'Services: DNS Resolver: Access Lists: Edit\' page.');
echo gettext('Allow access to the \'Firewall: NAT: 1:1: Edit\' page.');
echo gettext('Allow access to the \'Diagnostics: Tables\' page.');
echo gettext('Allow access to the \'System: Group manager\' page.');
echo gettext('Allow access to the \'System: User Manager: settings\' page.');
echo gettext('Allow access to the \'Status: DHCPv6 leases\' page.');
echo gettext('Edit Interface LAGG');
echo gettext('Allow access to the \'Status: NTP Serial GPS\' page.');
echo gettext('Indicates whether the user is allowed to dial in via L2TP');
echo gettext('Allow access to the \'Status: Load Balancer: Pool\' page.');
echo gettext('Allow access to the \'Interfaces: QinQ\' page.');
echo gettext('Allow access to the \'Interfaces: Bridge : Edit\' page.');
echo gettext('Allow access to the \'Interfaces: Wireless\' page.');
echo gettext('Allow access to the \'Services: Dynamic DNS clients\' page.');
echo gettext('Allow access to the \'Status: System logs: System: Wireless\' page.');
echo gettext('Allow access to the \'Firewall: Schedules: Edit\' page.');
echo gettext('Allow access to the \'Diagnostics: Ping\' page.');
echo gettext('Allow access to the \'System: Certificate Manager\' page.');
echo gettext('Allow access to the \'System: Gateways: Edit Gateway Groups\' page.');
echo gettext('Allow access to the \'System: Static Routes: Edit route\' page.');
echo gettext('Allow access to the \'Services: Wake on LAN\' page.');
echo gettext('Allow access to the \'System: License\' page.');
echo gettext('Allow access to the \'Services: DNS Filter\' page.');
echo gettext('Allow access to the \'Services: DNS Resolver\' page.');
echo gettext('Allows access to the \'Diagnostics: pfTop\' page');
echo gettext('Allow access to the \'Interfaces: GIF\' page.');
echo gettext('Allow access to the \'VPN: IPsec: Edit Pre-Shared Keys\' page.');
echo gettext('Allow access to the \'Services: Dynamic DNS client\' page.');
echo gettext('Allow access to the \'Services: PPPoE Server: Edit\' page.');
echo gettext('Allow access to the \'Diagnostics: Logs: PPPoE\' page.');
echo gettext('Allow access to the \'System: Advanced: Tunables\' page.');
echo gettext('Allow access to the \'System: Group Manager: Add Privileges\' page.');
echo gettext('Allow access to the \'Services: Load Balancer: Monitors\' page.');
echo gettext('Indicates whether the user is allowed to dial in via PPTP');
echo gettext('Allow access to the \'Diagnostics: Traceroute\' page.');
echo gettext('Allow access to the \'Firewall: NAT: Outbound\' page.');
echo gettext('Allow access to the \'System: Advanced: Firewall and NAT\' page.');
echo gettext('Allow access to the \'System: Gateways\' page.');
echo gettext('Allow access to the \'Firewall: Easy Rule\' add/status page.');
echo gettext('Allow access to the \'System: Static Routes\' page.');
echo gettext('Allow access to the \'XMLRPC Interface Stats\' page.');
echo gettext('Allow access to the \'Interfaces: Bridge\' page.');
echo gettext('Allow access to the \'System: High Availability\' page.');
echo gettext('Allow access to the \'Diagnostics: Factory defaults\' page.');
echo gettext('Allow access to the \'Services: DHCP Relay\' page.');
echo gettext('Allow access to the \'System: Firmware: Manual Update: Progress bar\' page.');
echo gettext('Allow access to the \'Services: Igmpproxy\' page.');
