<?php
/**
 *    Copyright (C) 2015 Deciso B.V.
 *
 *    All rights reserved.
 *
 *    Redistribution and use in source and binary forms, with or without
 *    modification, are permitted provided that the following conditions are met:
 *
 *    1. Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *
 *    2. Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 *    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 *    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 *    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 *    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 *    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 *    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 *    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *    POSSIBILITY OF SUCH DAMAGE.
 *
 */

/**
 *
 * Language support, autogenerated file
 *
 */
echo gettext('Change password');
echo gettext('User');
echo gettext('Certificates');
echo gettext('Certificate Authority');
echo gettext('Certification Revocation');
echo gettext('Certificates');
echo gettext('Firmware');
echo gettext('High Availability');
echo gettext('Routing');
echo gettext('General');
echo gettext('Admin Access');
echo gettext('Firewall/NAT');
echo gettext('Networking');
echo gettext('Miscellaneos');
echo gettext('System Tunables');
echo gettext('Notifications');
echo gettext('Settings');
echo gettext('Setup Wizard');
echo gettext('Users');
echo gettext('Groups');
echo gettext('Settings');
echo gettext('Servers');
echo gettext('User Manager');
echo gettext('System');
echo gettext('Interface Addignments');
echo gettext('Interface Groups');
echo gettext('Wireless');
echo gettext('VLANs');
echo gettext('QinQs');
echo gettext('PPPs');
echo gettext('GRE');
echo gettext('GIF');
echo gettext('Bridges');
echo gettext('LAGG');
echo gettext('(Assign)');
echo gettext('Interfaces');
echo gettext('IP');
echo gettext('Ports');
echo gettext('URLs');
echo gettext('All');
echo gettext('Aliases');
echo gettext('Port Forward');
echo gettext('1:1');
echo gettext('Outbound');
echo gettext('NPt');
echo gettext('NAT');
echo gettext('Floating');
echo gettext('Interface');
echo gettext('Rules');
echo gettext('Schedules');
echo gettext('Traffic Shaper');
echo gettext('Virtual IPs');
echo gettext('Firewall');
echo gettext('IP');
echo gettext('MAC');
echo gettext('Voucher');
echo gettext('FileManager');
echo gettext('Captive Portal');
echo gettext('DHCP Relay');
echo gettext('DHCP Server');
echo gettext('DHCPv6 Relay');
echo gettext('RouterAdvertisement');
echo gettext('DHCPv6 Server/RA');
echo gettext('DNS Filter');
echo gettext('DNS Forwarder');
echo gettext('Advanced');
echo gettext('ACLs');
echo gettext('DNS Resolver');
echo gettext('DynamicDNSRFC2136Clients');
echo gettext('DynamicDNSEdit');
echo gettext('Dynamic DNS');
echo gettext('IGMP Proxy');
echo gettext('VirtualServer');
echo gettext('Monitors');
echo gettext('Settings');
echo gettext('Load Balancer');
echo gettext('Network Time Protocol');
echo gettext('PPPoE Server');
echo gettext('Proxy Server');
echo gettext('SNMP');
echo gettext('Universal Plug and Play');
echo gettext('Wake on LAN');
echo gettext('Intrusion Detection');
echo gettext('Services');
echo gettext('MobileClients');
echo gettext('Keys');
echo gettext('AdvancedSettings');
echo gettext('IPsec');
echo gettext('L2TPUsers');
echo gettext('L2TP');
echo gettext('Client');
echo gettext('CSC');
echo gettext('Wizards');
echo gettext('ClientExport');
echo gettext('SharedKeyExport');
echo gettext('OpenVPN');
echo gettext('PPTPUsers');
echo gettext('PPTP');
echo gettext('VPN');
echo gettext('Captive Portal');
echo gettext('CARP');
echo gettext('DHCP IPv4 Leases');
echo gettext('DHCP IPv6 Leases');
echo gettext('Filter Reload');
echo gettext('GatewayGroups');
echo gettext('Gateways');
echo gettext('Interfaces');
echo gettext('Leases');
echo gettext('SAD');
echo gettext('SPD');
echo gettext('IPsec');
echo gettext('VirtualServers');
echo gettext('Load Balancer');
echo gettext('NTP');
echo gettext('OpenVPN');
echo gettext('Settings');
echo gettext('RRD Graphs');
echo gettext('Services');
echo gettext('Gateways');
echo gettext('Routing');
echo gettext('Resolver');
echo gettext('Wireless');
echo gettext('System');
echo gettext('DynamicView');
echo gettext('SummaryView');
echo gettext('Firewall');
echo gettext('DHCP');
echo gettext('PortalAuth');
echo gettext('IPsec');
echo gettext('PPP');
echo gettext('VPN');
echo gettext('LoadBalancer');
echo gettext('OpenVPN');
echo gettext('NTP');
echo gettext('Proxy');
echo gettext('Settings');
echo gettext('System Logs');
echo gettext('Traffic Graphs');
echo gettext('Universal Plug and Play');
echo gettext('Status');
echo gettext('ARP Table');
echo gettext('Authentication');
echo gettext('History');
echo gettext('Backup & Restore');
echo gettext('Crash Reporter');
echo gettext('DNS Lookup');
echo gettext('Factory Defaults');
echo gettext('Halt System');
echo gettext('Limiter Info');
echo gettext('NDP Table');
echo gettext('Packet Capture');
echo gettext('pfInfo');
echo gettext('pfTop');
echo gettext('Ping');
echo gettext('Reboot');
echo gettext('Routes');
echo gettext('SMART Status');
echo gettext('Sockets');
echo gettext('States');
echo gettext('States Summary');
echo gettext('System Activity');
echo gettext('Tables');
echo gettext('Test Port');
echo gettext('Traceroute');
echo gettext('Diagnostics');
echo gettext('About this Page');
echo gettext('Developers Wiki');
echo gettext('Documentation');
echo gettext('FreeBSD Handbook');
echo gettext('Paid Support');
echo gettext('UserForum');
echo gettext('Help');
echo gettext('menu');
echo gettext('test');
echo gettext('you should input a valid email address');
echo gettext('sid should be a number');
echo gettext('Related cron not found');
echo gettext('ICP port needs to be an integer value between 1 and 65535');
echo gettext('Specify a positive cache size. (number of MB\'s)');
echo gettext('Specify a positive number of first-level subdirectories.');
echo gettext('Specify a positive number of second-level subdirectories.');
echo gettext('Specify the maximum download size. (number of KB\'s)');
echo gettext('Specify the maximum upload size. (number of KB\'s)');
echo gettext('Specify the overall bandwidth for downloads in kilobits per second.');
echo gettext('Specify the per host bandwidth for downloads in kilobits per second.');
echo gettext('Proxy port needs to be an integer value between 1 and 65535');
echo gettext('FTP Proxy port needs to be an integer value between 1 and 65535');
echo gettext('The filename may only contain letters,digits and one dot (not required).');
echo gettext('This does not look like a valid url.');
echo gettext('Credentials TTL needs to be an integer value above 0');
echo gettext('Number of children needs to be an integer value above 0');
echo gettext('Pipe number must be between 1...65535');
echo gettext('Bandwidth out of range');
echo gettext('Bandwidth metric should be one of bit,Kbit,Mbit');
echo gettext('The burst value is an integer and represent a number of bytes.');
echo gettext('queue size should be between 2...100');
echo gettext('origin should be regular text of max 30 characters');
echo gettext('Description should be a string between 1 and 255 characters');
echo gettext('Queue number must be between 1...65535');
echo gettext('Related pipe not found');
echo gettext('Weight must be between 1...100');
echo gettext('Description should be a string between 1 and 255 characters');
echo gettext('origin should be regular text of max 30 characters');
echo gettext('provide a valid sequence for sorting');
echo gettext('Related pipe or queue not found');
echo gettext('origin should be regular text of max 30 characters');
echo gettext('Origin should be regular text of max 30 characters');
echo gettext('Value needs to be between 0 and 59, multiple values, ranges and * are supported (ex. 1,10,20,30 or 1-30  )');
echo gettext('Value needs to be between 0 and 23, multiple values, ranges and * are supported (ex. 1,2,8 or 0-8 )');
echo gettext('Value needs to be between 1 and 31, multiple values, ranges, L (last day of month) and * are supported (ex. 1,2,8 or 1-28  )');
echo gettext('Value needs to be between 1 and 12 or JAN to DEC, multiple values, ranges and * are supported (ex. JAN,2,10 or 3-8 )');
echo gettext('Value needs to be between 0 and 6 ( Sunday to Saturday), multiple values, ranges and * are supported (ex. 1,2,4 or 0-4  ) ');
echo gettext('Select a command from the list.');
echo gettext('Enter valid parameter(s) for the chosen command (Found illegal characters).');
echo gettext('Enter a description.');
