#!/bin/sh

/sbin/pfctl -i ${1} -Fs

/bin/rm -f /tmp/${1}_router
/bin/rm -f /tmp/${1}_routerv6
/bin/rm -f /tmp/${1}_searchdomain
/bin/rm -f /tmp/${1}_searchdomainv6
/bin/rm -f /tmp/nameserver_${1}
/bin/rm -f /tmp/nameserver_v6${1}
