#!/bin/sh

/sbin/pfctl -i $1 -Fs

/bin/rm -f /tmp/$1_router
/bin/rm -f /tmp/$1_routerv6
/bin/rm -f /tmp/$1up
/bin/rm -f /tmp/$1upv6
/bin/rm -f /var/etc/nameserver_v6$1
/bin/rm -f /var/etc/nameserver_$1
/bin/rm -f /var/etc/searchdomain_$1
/bin/rm -f /var/etc/searchdomain_v6$1

/usr/local/opnsense/service/configd_ctl.py filter reload
