#!/bin/sh

# let the configuration system know that the ip has changed.
# /usr/local/opnsense/service/configd_ctl.py interface newip $interface

ROUTER="/tmp/${1}_router"
if [ -n "${route_vpn_gateway}" ]; then
	/bin/echo ${route_vpn_gateway} > "${ROUTER}"
elif [ -n "${ifconfig_remote}" ]; then
	/bin/echo ${ifconfig_remote} > "${ROUTER}"
else
	# PATCH: 4133 - bad gateway being set
	if_gateway="$(
		/sbin/ifconfig ${1} inet | \
		/usr/bin/fgrep "inet " | \
		/usr/bin/fgrep " --> " | \
		/usr/bin/awk '{ print $4 }'
	)"
	if [ -n "${if_gateway}" ] ; then
		/bin/echo ${if_gateway} > "${ROUTER}"
	elif [ -n "${ifconfig_local}" ]; then
		/bin/echo ${ifconfig_local} > "${ROUTER}"
	elif [ "${dev_type}" = "tun" ]; then
		/bin/echo ${5} > "${ROUTER}"
	fi
fi

ROUTERV6="${ROUTER}v6"
if [ -n "${route_ipv6_gateway_1}" ]; then
	/bin/echo ${route_ipv6_gateway_1} > "${ROUTERV6}"
elif [ -n "${ifconfig_ipv6_remote}" ]; then
	/bin/echo ${ifconfig_ipv6_remote} > "${ROUTERV6}"
else
	# PATCH: 4133 - bad gateway being set
	if_ipv6_gateway="$(
		/sbin/ifconfig ${1} inet6 | \
		/usr/bin/fgrep "inet " | \
		/usr/bin/fgrep " --> " | \
		/usr/bin/awk '{ print $4 }'
	)"
	if [ -n "${if_ipv6_gateway}" ] ; then
		/bin/echo ${if_ipv6_gateway} > "${ROUTERV6}"
	elif [ -n "${ifconfig_ipv6_local}" ]; then
		/bin/echo ${ifconfig_ipv6_local} > "${ROUTERV6}"
	fi
fi

/usr/bin/touch "/tmp/${1}up"
/usr/bin/touch "/tmp/${1}upv6"

/usr/local/opnsense/service/configd_ctl.py interface newip "${1}"

# If there's a setting for "additional --up script", then run that, but
# within a subshell so we don't mess up the containing environment,
# and we don't cause problems for the other stuff

exit 0
