#!/bin/sh

USB_RESET_ON="<usbconfig_reset>1</usbconfig_reset>"

if [ -f /conf/config.xml ]; then
    if [ "$(grep -c "${USB_RESET_ON}" /conf/config.xml)" != "0" ]; then
        /usr/sbin/usbconfig reset >/dev/null 2>&1
    fi
fi
