#!/bin/sh

# Perform major updates

if opnsense-update -B; then
	# reroot only, we swapped the base files
	reboot -r
fi

if opnsense-update -P; then
	# reboot to load properly including boot screen
	reboot
fi
