#!/bin/sh

# Restore backups from previous shutdown
/usr/local/etc/rc.syshook backup restore

# Flush cache, kind of a backup now and maybe even more so in the future
# XXX also requires an echo -n
#configctl unbound cache flush
