#!/bin/sh

# Copyright (c) 2025 Franco Fichtner <franco@opnsense.org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

OWNER="wwwonly:wheel"

# set up required output directories for various PHP components
for PHPDIR in cache sessions tmp; do
	PHPDIR=/var/lib/php/${PHPDIR}

	mkdir -p ${PHPDIR}
	# XXX assess the need to chmod subdirectories not cleared by var script
	chmod 750 ${PHPDIR}

	# important note: ownership change may fail when user is not known
	chown -R ${OWNER} ${PHPDIR}
done

# change ownership for GUI related file access
find /conf -name 'vouchers_*.db' -exec chown ${OWNER} {} \;
find /conf/backup -name '*.xml' -exec chown ${OWNER} {} \;
for PHPOWN in /conf /conf/config.xml /conf/backup /var/run/booting; do
	chown ${OWNER} ${PHPOWN}
done

# flush Phalcon volt templates
find /var/lib/php/cache -name '*.php' -exec rm {} \;
