.\"
.\" Copyright (c) 2018 Franco Fichtner <franco@opnsense.org>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\"
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd Sep 16, 2018
.Dt OPNSENSE-VERSION 8
.Os
.Sh NAME
.Nm opnsense-version
.Nd OPNsense version utility
.Sh SYNOPSIS
.Nm
.Op Fl aNnVv
.Sh DESCRIPTION
The
.Nm
utility emits release package metadata, e.g. build parameters
and product-relevant information including copyrights for full
branding capabilities.
.Pp
Callers use this metadata to configure the system, return user
information or to construct links for firmware upgrades using
.Xr opnsense-update 8 .
It is similar to
.Xr opnsense-verify 8 Ap s
.Sq Fl a
parameter, but not intended to handle operating system information.
.Pp
The options are as follows:
.Bl -tag -width ".Fl a" -offset indent
.It Fl a
Return the firmware ABI string.
.It Fl N
Return the product name.
.It Fl n
Return the release package name.
.It Fl V
Return the product name followed by its version.
.It Fl v
Return the release package version.
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa /usr/local/opnsense/version/opnsense
The version metadata file of the release package.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr opnsense-update 8 ,
.Xr opnsense-verify 8
.Sh HISTORY
The
.Nm
utility first appeared in OPNsense 18.7.?.
.Sh AUTHORS
.An Franco Fichtner Aq Mt franco@opnsense.org
