.\"
.\" Copyright (c) 2018-2021 Franco Fichtner <franco@opnsense.org>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\"
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd April 21, 2021
.Dt OPNSENSE-IMPORTER 8
.Os
.Sh NAME
.Nm opnsense-importer
.Nd OPNsense import utility
.Sh SYNOPSIS
.Nm
.Op Fl bpz
.Op Ar disk
.Sh DESCRIPTION
The
.Nm
utility can import a previous configuration from multiple types of
disk formats.
A normal system directory layout using
.Pa /conf
is expected with at least
.Pa /conf/config.xml
present.
If successful, the old configuration will be replaced.
.Pp
The
.Ar disk
selection allows the user to escape to a shell by issuing
.Sq \&!
instead.
This shell can be used to e.g. start an early install process using
.Xr opnsense-installer 8 .
.Pp
The options are as follows:
.Bl -tag -width ".Fl b" -offset indent
.It Fl b
Run the importer in boot mode, which only triggers the import timeout
prompt when no current configuration is found in the system.
This mode is used for install media duties to allow early configuration
imports to be able to live-boot into them afterwards.
.It Fl p
Run the importer in password reset mode, which mounts the disk and
invokes the builtin root password prompt and after change adjusts
authentication settings to know good defaults.
.It Fl z
List all available ZFS pools in the system and exit.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr opnsense-installer 8
.Sh HISTORY
The
.Nm
utility first appeared in OPNsense 17.1.4.
It was derived from code written for the
.Xr opnsense-installer 8
utility.
.Sh AUTHORS
.An Franco Fichtner Aq Mt franco@opnsense.org
