.\"
.\" Copyright (c) 2021 Franco Fichtner <franco@opnsense.org>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\"
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd July 7, 2021
.Dt OPNSENSE-BEEP 8
.Os
.Sh NAME
.Nm opnsense-beep
.Nd OPNsense beep utility
.Sh SYNOPSIS
.Nm
.Op Ar melody
.Sh DESCRIPTION
The
.Nm
utility will emit system beeps or melodies.
.Pp
Default melodies are as follows:
.Pp
.Bl -bullet -compact
.It
.Ar high
.It
.Ar low
(default)
.It
.Ar start
.It
.Ar stop
.El
.Pp
Argument given will load the melody file from the database directory.
Local files can be added at will.
All files including the defaults can be overwritten by appending
.Sq .local
to a file name.
.Pp
The file format is one note value followed by a duration value per line
as understood by
.Xr beep 1 .
.Sh FILES
.Bl -tag -width Ds
.It Pa /usr/local/etc/opnsense-beep.d
The melody database directory.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr beep 1
.Sh AUTHORS
.An Scott Ullrich Aq Mt sullrich@gmail.com
