
                <footer class="page-foot col-sm-push-2">
        			<div class="container-fluid">
        				<a target="_blank" href="<?=$g['product_website_footer']?>" class="redlnk"><?=$g['product_name']?></a> is &copy;
	 <?=$g['product_copyright_years']?> by <a href="<?=$g['product_copyright_url']?>" class="tblnk"><?=$g['product_copyright']?></a>. All Rights Reserved.
	[<a href="/license.php" class="tblnk">view license</a>] 
        			</div>
        		</footer>
        
        	</div>
        	<!-- /row-->
        
		</main>	
		
		<div class="modal fade" id="modal_widgets" tabindex="-1" role="dialog" aria-labelledby="modal_widgets_label" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="modal_widgets_label">Widgets</h4>
                    </div>
                
                    <div class="modal-body">
                        <table class="table table-striped table-hover">
                            <tr><td>pfSense.localdomain</td></tr>
                            <tr><td>pfSense.localdomain</td></tr>
                            <tr><td>pfSense.localdomain</td></tr>
                            <tr><td>pfSense.localdomain</td></tr>
                            <tr><td>pfSense.localdomain</td></tr>
                            <tr><td>pfSense.localdomain</td></tr>
                            <tr><td>pfSense.localdomain</td></tr>
                        </table>
                    </div>
                
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Add widgets</button>
                    </div>
                </div><!-- /modal-content -->
            </div><!-- /modal-dialog -->
        </div><!-- /modal -->
	
	
	</body>
</html>