# logfilename			[owner:group]	mode	count	size	when	flags	[/pid_file]				[sig_num]
{% if not helpers.empty('OPNsense.IDS.general.enabled') %}
/var/log/suricata/eve.json	root:wheel	640	{{ OPNsense.IDS.general.eveLog.rotate.count }}	{{ OPNsense.IDS.general.eveLog.rotate.size }}	${{ OPNsense.IDS.general.eveLog.rotate.frequency }}	B	/var/run/suricata.pid	1
{% endif %}
