filter f_local_lockout_auth {
  facility(auth);
};

destination d_local_lockout_auth {
    program("/usr/local/opnsense/scripts/syslog/lockout_handler");
};

rewrite r_lo_strip_newlines {
    subst("\r?\n", " ", value("MESSAGE"), type("pcre"), flags("global"));
};

log {
    source(s_all);
    rewrite(r_lo_strip_newlines);
    filter(f_local_lockout_auth);
    destination(d_local_lockout_auth);
};
