#!/bin/sh

# refresh relevant configuration files
/usr/local/etc/rc.configure_firmware

# create a unique timestamp for our asset caching
touch /usr/local/opnsense/www/index.php

# remove spurious .pkgsave files pkg may have created
for DIR in /boot /usr/libexec/bsdinstall /usr/local; do
	daemon -f find ${DIR} -type f -name "*.pkgsave" -delete
done

# remove our stale pyc files not handled by pkg
daemon -f find /usr/local/opnsense -type f -name "*.pyc" -delete
