[reload]
command:/usr/local/opnsense/scripts/shaper/start.sh dnctl
parameters:
type:script
message:restarting dummynet

[reset]
command:/usr/local/opnsense/scripts/shaper/reset_aqm.sh
parameters:
type:script
message:resetting dummynet AQM state

[stats]
command:/usr/local/opnsense/scripts/shaper/dummynet_stats.py
parameters:
type:script_output
message:request dummynet stats
