[configure.dns]
command:/usr/local/sbin/pluginctl -c dns
parameters:
type:script
message:reconfiguring DNS subsystem

[configure.dhcp]
command:/usr/local/sbin/pluginctl -c dhcp
parameters:
type:script
message:reconfiguring DHCP subsystem
