[trim]
command:/usr/sbin/daemon -f /sbin/zpool trim
parameters:%s
type:script
message:Trimming ZFS pool %s
description:ZFS pool trim

[scrub]
command:/usr/sbin/daemon -f /sbin/zpool scrub
parameters:%s
type:script
message:Scrubbing ZFS Pool %s
description:ZFS pool scrub

[status]
command:/sbin/zpool status -j --json-int
parameters:
type:script_output
message:Reading ZFS pool status
description:ZFS pool status

[snapshot.list]
command:/usr/local/opnsense/scripts/system/bectl.py
parameters:list
type:script_output
message:List snapshots

[snapshot.create]
command:/usr/local/opnsense/scripts/system/bectl.py
parameters: create --beName=''%s
type:script_output
message:Creating snapshot %s
allowed_groups:wheel,wwwonly

[snapshot.clone]
command:/usr/local/opnsense/scripts/system/bectl.py
parameters: clone --from-source=''%s --beName=''%s
type:script_output
message:Cloning snapshot %s from %s
allowed_groups:wheel,wwwonly

[snapshot.activate]
command:/usr/local/opnsense/scripts/system/bectl.py
parameters: activate --beName=''%s
type:script_output
message:Activate snapshot %s
allowed_groups:wheel,wwwonly

[snapshot.destroy]
command:/usr/local/opnsense/scripts/system/bectl.py
parameters: destroy --beName=''%s
type:script_output
message:Delete snapshot %s
allowed_groups:wheel,wwwonly

[snapshot.rename]
command:/usr/local/opnsense/scripts/system/bectl.py
parameters: rename --from-source=''%s --beName=''%s
type:script_output
message:Rename snapshot %s to %s
allowed_groups:wheel,wwwonly

[snapshot.supported]
command:/usr/local/opnsense/scripts/system/bectl.py
parameters: is_supported
type:script_output
message:Checking if ZFS is supported
