[configure]
command:/usr/local/opnsense/scripts/opendns/configure.php && { /usr/local/sbin/pluginctl -c dns_reload > /dev/null || { echo "dns_reload failed"; exit 1; }; } && { /usr/local/sbin/pluginctl -c dhcp > /dev/null || { echo "dhcp reload failed"; exit 1; }; } && echo ok
parameters:
type:script_output
errors:no
message:Configuring OpenDNS
