#!/usr/local/bin/php
<?php

/*
 * Copyright (C) 2021 Deciso B.V.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/* XXX use legacy code to generate certs and CAs */

require_once("config.inc");
require_once("certs.inc");

$store = new OPNsense\Trust\Store();
$instances = [];
@mkdir("/usr/local/etc/syslog-ng/cert.d", 0700, true);
foreach ((new OPNsense\Syslog\Syslog())->destinations->destination->iterateItems() as $id => $item) {
    if (in_array($item->transport, ['tls4', 'tls6']) && (string)$item->enabled == "1"){
        $dest_key = str_replace("-", "", $id);
        $instances[] = $dest_key;
        $cert = $store->getCertificate((string)$item->certificate);
        if ($cert && isset($cert['prv'])) {
            file_put_contents("/usr/local/etc/syslog-ng/cert.d/{$dest_key}.key", $cert['prv']);
            file_put_contents("/usr/local/etc/syslog-ng/cert.d/{$dest_key}.crt", $cert['crt']);
        }
    }
}

// cleanup old/unused certs
foreach (glob("/usr/local/etc/syslog-ng/cert.d/*") as $filename) {
    $instance = explode(".", basename($filename))[0];
    $ext = pathinfo($filename)['extension'];
    if (!in_array($instance, $instances) && in_array($ext, ['crt', 'key'])) {
        unlink($filename);
    }
}
