#!/usr/local/bin/php
<?php

/*
 * Copyright (C) 2021-2026 Deciso B.V.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

require_once("script/load_phalcon.php");

use OPNsense\Core\File;
use OPNsense\Syslog\Syslog;
use OPNsense\Trust\Store;

$store = new Store();
$filenames = [];
$targetdir = "/usr/local/etc/syslog-ng/cert.d";
@mkdir($targetdir, 0700, true);
foreach ((new Syslog())->destinations->destination->iterateItems() as $id => $item) {
    if (in_array($item->transport, ['tls4', 'tls6']) && !$item->enabled->isEmpty()){
        if (($cert = $store->getCertificate((string)$item->certificate)) && isset($cert['prv'])) {
            $basename = $targetdir . "/" . str_replace("-", "", $id);
            foreach (['prv' => "{$basename}.key", 'crt' => "{$basename}.crt"] as $key => $filename) {
                File::file_update_contents($filename, $cert[$key], 0640);
                $filenames[] = $filename;
            }
        }
    }
}
// cleanup old/unused certs
foreach (glob("/usr/local/etc/syslog-ng/cert.d/*.{crt,key}", GLOB_BRACE) as $filename) {
    if (!in_array($filename, $filenames)) {
        unlink($filename);
    }
}
