#!/usr/local/bin/php
<?php

/*
 * Copyright (c) 2024-2025 Franco Fichtner <franco@opnsense.org>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

require_once 'config.inc';
require_once 'util.inc';
require_once 'system.inc';
require_once 'interfaces.inc';

/**
 * Check if a down gateway has a viable failover target using the same logic
 * as Gateways::getGroups(). Without a viable target, killing states only
 * causes a self-inflicted outage with no benefit.
 *
 * Checks two failover paths:
 *   1. Gateway groups: another member of the same group is UP (per trigger settings)
 *   2. Default gateway switching: another gateway of the same protocol family is UP
 *
 * @param string $gwname         Name of the gateway that is down
 * @param array  $all_statuses   Full return_gateways_status() keyed by name
 * @return bool  true if a viable failover target exists
 */
function has_viable_failover_target($gwname, $all_statuses)
{
    global $config;

    $down_gw = $all_statuses[$gwname] ?? null;
    if ($down_gw === null) {
        return false;
    }

    /* Check gateway groups: use same logic as Gateways::getGroups() */
    foreach (config_read_array('gateways', 'gateway_group') as $group) {
        if (empty($group['item'])) {
            continue;
        }

        /* is this down gateway a member of this group? */
        $is_member = false;
        foreach ($group['item'] as $item) {
            $itemsplit = explode('|', $item);
            if ($itemsplit[0] == $gwname) {
                $is_member = true;
                break;
            }
        }

        if (!$is_member) {
            continue;
        }

        $trigger = isset($group['trigger']) ? (string)$group['trigger'] : '';

        /* check all other members of this group for viability */
        foreach ($group['item'] as $item) {
            $itemsplit = explode('|', $item);
            $member_name = $itemsplit[0];

            if ($member_name == $gwname) {
                continue;
            }

            if (empty($all_statuses[$member_name])) {
                continue;
            }

            $member_status = $all_statuses[$member_name]['status'];

            /*
             * Mirror the status evaluation from Gateways::getGroups()
             * to determine if this member is considered UP for this group.
             */
            switch ($member_status) {
                case 'down':
                case 'force_down':
                    $is_up = false;
                    break;
                case 'delay+loss':
                    $is_up = stristr($trigger, 'latency') === false &&
                             stristr($trigger, 'loss') === false;
                    break;
                case 'delay':
                    $is_up = stristr($trigger, 'latency') === false;
                    break;
                case 'loss':
                    $is_up = stristr($trigger, 'loss') === false;
                    break;
                default:
                    $is_up = true;
            }

            if ($is_up) {
                return true;
            }
        }
    }

    /* Check default gateway switching: another gateway of the same family is UP */
    if (isset($config['system']['gw_switch_default'])) {
        foreach ($all_statuses as $name => $candidate) {
            if ($name == $gwname) {
                continue;
            }
            if (($candidate['ipprotocol'] ?? '') != ($down_gw['ipprotocol'] ?? '')) {
                continue;
            }
            if (strpos($candidate['status'], 'down') === false) {
                return true;
            }
        }
    }

    return false;
}

$gwnames = [];
$affected_gateways = !empty($argv[1]) ? explode(',', $argv[1]) : [];

$metered_found_prios = ['inet' => 256, 'inet6' => 256];
$metered_gws = ['inet' => [], 'inet6' => []];

/* collect all statuses first so we can check for viable failover targets */
$all_statuses = return_gateways_status();

foreach ($all_statuses as $status) {
    if (strpos($status['status'], 'down') !== false) {
        /* recover monitors stuck in down state ignoring "force_down" */
        if ($status['status'] == 'down') {
            $gwnames[] = $status['name'];
        }
        /* kill states for all down transitions including "force_down" */
        if (!empty($status['monitor_killstates']) && in_array($status['name'], $affected_gateways)) {
            if (has_viable_failover_target($status['name'], $all_statuses)) {
                $uuid = trim(configdp_run('filter kill gateway_states', [$status['gateway']], true));
                log_msg("ROUTING: killing states for unreachable gateway {$status['name']} [$uuid]", LOG_NOTICE);
            } else {
                log_msg("ROUTING: skipping state kill for gateway {$status['name']}, no viable failover target", LOG_NOTICE);
            }
        }
    } else {
        /* collect "metered" gateways for all non-down status reports */
        if (!empty($status['monitor_killstates_priority'])) {
            $metered_gws[$status['ipprotocol']][] = $status;
	/* only consider currently affected gateways as priority candidates */
        } elseif (in_array($status['name'], $affected_gateways)) {
            $metered_found_prios[$status['ipprotocol']] = min($status['priority'], $metered_found_prios[$status['ipprotocol']]);
        }
    }
}

foreach ($metered_found_prios as $ipproto => $metered_found_prio) {
    /* kill states for "metered" gateways */
    foreach ($metered_gws[$ipproto] as $status) {
        if ($status['priority'] > $metered_found_prio) {
            $uuid = trim(configdp_run('filter kill gateway_states', [$status['gateway']], true));
            log_msg("ROUTING: killing states for deferred gateway {$status['name']} [$uuid]", LOG_NOTICE);
        }
    }
}

plugins_configure('monitor', true, [$gwnames]);
