#!/bin/sh

# Copyright (c) 2018 Franco Fichtner <franco@opnsense.org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
# OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

VERSION="/usr/local/opnsense/version/opnsense"
OUTPUT=

if [ ! -f ${VERSION} ]; then
	echo "Missing ${VERSION}" >&2
	exit 1
fi

eval "$(grep -v '[{}]' ${VERSION} | sed 's/[^"]*"\([^"]*\)"[^"]*"\([^"]*\)".*/\1="\2"/')"

while getopts aNnVv OPT; do
	case ${OPT} in
	a)
		if [ -n "${OUTPUT}" ]; then
			OUTPUT="${OUTPUT} "
		fi
		OUTPUT="${OUTPUT}\${product_abi}"
		;;
	N)
		if [ -n "${OUTPUT}" ]; then
			OUTPUT="${OUTPUT} "
		fi
		OUTPUT="${OUTPUT}\${product_name}"
		;;
	n)
		if [ -n "${OUTPUT}" ]; then
			OUTPUT="${OUTPUT} "
		fi
		OUTPUT="${OUTPUT}\${product_id}"
		;;
	v)
		if [ -n "${OUTPUT}" ]; then
			OUTPUT="${OUTPUT} "
		fi
		OUTPUT="${OUTPUT}\${product_version}"
		;;
	*)
		echo "Usage: man opnsense-version" >&2
		exit 1
		;;
	esac
done

shift $((${OPTIND} - 1))

if [ -z "${OUTPUT}" ]; then
	OUTPUT="\${product_name} \${product_version} \(\${product_arch}/\${product_flavour}\)"
fi

eval echo ${OUTPUT}
