#!/bin/sh

# Copyright (C) 2020-2021 Franco Fichtner <franco@opnsense.org>
# Copyright (C) 2005 Scott Ullrich <sullrich@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
# OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

COMMAND=${1}

START="500 400 600 800 800"
STOP="600 800 500 400 400"

if [ ! -c "/dev/speaker" ]; then
	exit
fi

if [ -f /conf/config.xml ]; then
	if [ "$(/usr/bin/grep -c disablebeep /conf/config.xml)" != "0" ]; then
		exit
	fi
fi

case "${COMMAND}" in
start)
	for NOTE in ${START}; do /usr/local/bin/beep -p ${NOTE} 25; done
	;;
stop)
	for NOTE in ${STOP}; do /usr/local/bin/beep -p ${NOTE} 25; done
	;;
*)
	;;
esac
