#!/bin/sh

# Copyright (c) 2014-2024 Franco Fichtner <franco@opnsense.org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
# OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

__RUNNING_INSIDE_ATF_RUN=internal-yes-value
export __RUNNING_INSIDE_ATF_RUN

if [ "$(id -u)" != "0" ]; then
	echo "Must be root."
	exit 1
fi

TESTDIR=/usr/src/tests/sys/netpfil/pf
TESTFILE=${1:-unkown}

TEST=${TESTDIR}/${1}.sh

if [ ! -f "${TEST}" ]; then
	echo "Unsupported test case: ${TESTFILE}" >&2
	exit 1
fi

grep ^atf_test_case ${TEST} | tr -d '"' | awk '{ print $2 " " $3}' | while read CASE CLEANUP; do
	/usr/libexec/atf-sh ${TEST} ${CASE} > /dev/null 2>&1
	RET=${?}
	if [ -n "${CLEANUP}" ]; then
		/usr/libexec/atf-sh ${TEST} ${CASE}:cleanup > /dev/null 2>&1
	fi
	RESULT=failed
	if [ ${RET} -eq 0 ]; then
		RESULT=passed
	fi
	echo ">>> $(basename ${TESTDIR}):${TESTFILE}:${CASE}: ${RESULT}"
done
