#!/bin/sh

# Copyright (c) 2014-2021 Franco Fichtner <franco@opnsense.org>
# Copyright (c) 2004-2009 Scott Ullrich <sullrich@gmail.com>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
# OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

if [ "$(id -u)" != "0" ]; then
	echo "Must be root."
	exit 1
fi

rm -f /tmp/install_complete

bsdinstaller()
{
sysctl kern.geom.debugflags=16 >/dev/null
sysctl net.link.ether.inet.log_arp_wrong_iface=0 >/dev/null

ifconfig lo0 127.0.0.1
ifconfig lo0 inet6 ::1
ifconfig lo0 up

if [ -z "${TERM}" ]; then
	if [ -n "$(tty | grep ttyv)" ]; then
		export TERM=xterm
	else
		export TERM=vt100
	fi
fi

CONFIGDIR=/usr/local/share/dfuibe_lua
CONFIGS=${CONFIGDIR}/main.lua

for CONFIG in BSDInstaller FreeBSD Product; do
	if [ -f /usr/local/share/dfuibe_lua/conf/${CONFIG}.lua ]; then
		CONFIGS="${CONFIGS} ${CONFIGDIR}/conf/${CONFIG}.lua"
	fi
done

daemon -f lua50c51 ${CONFIGS}

conscontrol mute on > /dev/null

dfuife_curses -b /usr/local/share/dfuife_curses/hourglass.txt

conscontrol mute off > /dev/null
}

# XXX compat glue for now
if [ -e /usr/libexec/bsdinstall/opnsense ]; then
	bsdinstall opnsense
else
	bsdinstaller
fi

if [ ! -f /tmp/install_complete ]; then
	echo "The installation was aborted."
	echo
	exit
fi

clear

echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo "The installation finished successfully."
echo
echo "After reboot, open a web browser and navigate to"
echo "https://192.168.1.1 (or the LAN IP address).  The console"
echo "can also be used to set a different LAN IP."
echo
echo "Your browser may report the HTTPS certificate as untrusted"
echo "and ask you to accept it.  This is normal, as the default"
echo "certificate will be self-signed and cannot be validated by"
echo "an external root authority."
echo
echo -n "Rebooting in 5 seconds.  CTRL-C to abort"
for n in 5 4 3 2 1; do
    echo -n "."
    sleep 1
done
echo

reboot
