#!/bin/sh
if [ "$1" = "tls" ]; then
	(/usr/local/bin/php /usr/local/etc/inc/openvpn.tls-verify.php -d "$2" "$3")
	exit $?
else
	# Single quoting $password breaks getting the value from the variable.
	password=$(echo -n "${password}" | openssl enc -base64 | sed -e 's/=/%3D/g')
	username=$(echo -n "${username}" | openssl enc -base64 | sed -e 's/=/%3D/g')

	(/usr/local/bin/php /usr/local/etc/inc/openvpn.auth-user.php "$username" "$password" "$common_name" "$3" "$2" "$4")
	exit $?
fi

exit 1
