#!/usr/local/bin/php
<?php

/*
 * Copyright (C) 2019 Franco Fichtner <franco@opnsense.org>
 * Copyright (C) 2017 Alexander Shursha <kekek2@ya.ru>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

require_once 'config.inc';
require_once 'util.inc';
require_once 'system.inc';
require_once 'interfaces.inc';
require_once 'filter.inc';
require_once 'services.inc';
require_once 'auth.inc';

/*
 * -c is configure mode
 * -s is service mode
 */
$opts = getopt('cs', array(), $optind);
$args = array_slice($argv, $optind);

if (empty($args[0])) {
    $results = [];
    if (isset($opts['s'])) {
        foreach (services_get() as $service) {
            $results[$service['name']] = 1;
        }
    } else {
        foreach (plugins_scan() as $name => $path) {
            try {
                include_once $path;
            } catch (ParseError $e) {
                error_log($e);
            }
            $func = sprintf('%s_configure', $name);
            if (function_exists($func)) {
                foreach ($func() as $when => $worker) {
                    $results[$when] = 1;
                }
            }
        }
    }

    $results = array_keys($results);
    sort($results);

    foreach ($results as $result) {
        echo "$result\n";
    }

    exit(0);
}

if (isset($opts['s'])) {
    $name = !empty($args[0]) ? $args[0] : '';
    $act = !empty($args[1]) ? $args[1] : '';
    switch ($act) {
        case 'start':
            service_control_start($name, array());
            break;
        case 'stop':
            service_control_stop($name, array());
            break;
        case 'restart':
            service_control_restart($name, array());
            break;
        default:
            echo "Unknown command `$act'\n";
            break;
    }
    exit (0);
}

/* second argument is hook */
$hook = array_shift($args);
/* other arguments are passed as is */
plugins_configure($hook, true, $args);
